### ISSUE TITLE
好像没这个属性鸭onebot.OneBotConfig

### ISSUE THREAD

**Issue by zsq2010** [FishZe/go-libonebot#1]
主页代码加进去
./main.go:14:25: undefined: onebot.OneBotConfig

```
// 创建一份配置
	onebotConfig := onebot.OneBotConfig{PlatForm: "QQ", Version: "1.0.0", Implementation: "MyQQImpl"}
```

**Comment by FishZe** [comment]
README忘记修改了，参考 https://github.com/FishZe/go-libonebot/blob/7a6c0c8057875744b5e7ab6bb1e1244691a1c29f/example/main.go#L14 这里的代码吧
